builds:
  - goos:
      - darwin
      - linux

homebrew_casks:
  - repository:
      owner: staticaland
      name: pin-github-actions
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            # replace 'foo' with the actual binary name
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/foo"]
          end
