builds:
  - goos:
      - darwin
      - linux

homebrew_casks:
  - repository:
      owner: staticaland
      name: pin-github-actions
    hooks:
      post:
        install: |
          on_macos do
            if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
              system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pin-github-actions"]
            end
          end
