# This file was generated by GoReleaser. DO NOT EDIT.
cask "pin-github-actions" do
  desc ""
  homepage ""
  version "1.7.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pin-github-actions"

  on_macos do
    on_intel do
      url "https://github.com/staticaland/pin-github-actions/releases/download/v1.7.0/pin-github-actions_1.7.0_darwin_amd64.tar.gz"
      sha256 "3dacb300dd2797860189f197d18aabe97b7b6ee44bf2f4909fe43e142283e525"
    end
    on_arm do
      url "https://github.com/staticaland/pin-github-actions/releases/download/v1.7.0/pin-github-actions_1.7.0_darwin_arm64.tar.gz"
      sha256 "5b94e907bb42daaec44b21b9efef5e61eae6ba9c6f4de4baa1e4a1ffa2a05cc6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/staticaland/pin-github-actions/releases/download/v1.7.0/pin-github-actions_1.7.0_linux_amd64.tar.gz"
      sha256 "d1053cc3f18cecd8741d8e2ecae28bd4505a55c4ed1e0b69e5a8ca617def0eeb"
    end
    on_arm do
      url "https://github.com/staticaland/pin-github-actions/releases/download/v1.7.0/pin-github-actions_1.7.0_linux_arm64.tar.gz"
      sha256 "ba0a7cb37ac3c16b0b7d40c7274e33197f088ec72e7b5880d38a3f618fc1ca2c"
    end
  end

  on_macos do
    postflight do
      if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pin-github-actions"]
      end
    end
  end

  # No zap stanza required
end
