# This file was generated by GoReleaser. DO NOT EDIT.
cask "pin-github-actions" do
  desc ""
  homepage ""
  version "1.9.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pin-github-actions"

  on_macos do
    on_intel do
      url "https://github.com/staticaland/pin-github-actions/releases/download/v1.9.0/pin-github-actions_1.9.0_darwin_amd64.tar.gz"
      sha256 "f4cd252996e681fbf61e8338dbed617abe4b5f97b2d1ded20044f0659a9be173"
    end
    on_arm do
      url "https://github.com/staticaland/pin-github-actions/releases/download/v1.9.0/pin-github-actions_1.9.0_darwin_arm64.tar.gz"
      sha256 "80d9ab44e4c0c0ac56fd1f91ddcbf14d2fe2ee64a734c616abe45bdb8ba652ff"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/staticaland/pin-github-actions/releases/download/v1.9.0/pin-github-actions_1.9.0_linux_amd64.tar.gz"
      sha256 "cab8f6f8f6afa21b71ea1566434d378bdf373c67cdfdd90bb697056afc422766"
    end
    on_arm do
      url "https://github.com/staticaland/pin-github-actions/releases/download/v1.9.0/pin-github-actions_1.9.0_linux_arm64.tar.gz"
      sha256 "769865d9e1d434b7d83f93fcbe8ee08d83482387fcc701f9ed672f02b1b552b3"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      # replace 'foo' with the actual binary name
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/foo"]
    end
  end

  # No zap stanza required
end
